#!/bin/sh
#
#   "Rsyphon"
#
#   Copyright (C) 2002-2004  Brian Elliott Finley
#
#   $Id$
#
#
# Support for IRIX style chkconfig:
# chkconfig:   35 20 20
# description: The Rsyphon rsnetbootmond daemon.
#
#
# Support for LSB compliant init system:
### BEGIN INIT INFO
# Provides: rsyphon-server-netbootmond
# Required-Start: $network $syslog
# Required-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Rsyphon's daemon for net boot control
# Description: Rsyphon's daemon for controlling netboot clients.
#              If clients are configured to always boot from the network, 
#              rsnetbootmond can be configured to tell them to boot off their
#              local disks each time they boot after having completed a 
#              successful autoinstall.
### END INIT INFO


PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:
PIDFILE=/var/run/rsnetbootmond.pid

case "$1" in
  start)
    echo -n "Starting Rsyphon's net boot client monitor: "
    rsnetbootmond
    if pgrep rsnetbootmond >/dev/null 2>&1; then
        echo "ok."
        exit 0
    else
        echo "failed."
        exit 1
    fi
    ;;
  stop)
    echo -n "Stopping Rsyphon's net boot client monitor: "
    [ -f $PIDFILE ] && kill `cat $PIDFILE 2>/dev/null`
    if [ $? -eq 0 ]; then
        echo "ok."
        exit 0
    else
        echo "failed."
        exit 1
    fi
    ;;
  status)
    echo -n "Status of Rsyphon's net boot client monitor: rsnetbootmond... "
    ([ -f $PIDFILE ] && ps -p `cat $PIDFILE` >/dev/null 2>&1 && echo "running." && exit 0) || (echo "not running." && exit 1)
    ;;
  reload)
    echo "Not implemented."
    ;;
  force-reload|restart)
    sh $0 stop
    sh $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart}"
    exit 1
    ;;
esac

